# Generated by Django 4.2.7 on 2025-09-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, help_text='Técnico asignado al mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
