# Generated by Django 4.2.7 on 2025-09-15 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_tecnico_asignado_to_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatoriomantenimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Título del recordatorio', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del recordatorio')),
                ('fecha_programada', models.DateTimeField(help_text='Fecha y hora programada para el recordatorio')),
                ('tipo', models.CharField(choices=[('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('revision_general', 'Revisión General'), ('cambio_aceite', 'Cambio de Aceite'), ('cambio_llantas', 'Cambio de Llantas'), ('revision_frenos', 'Revisión de Frenos'), ('alineacion_balanceo', 'Alineación y Balanceo'), ('otros', 'Otros')], default='otros', help_text='Tipo de recordatorio', max_length=50)),
                ('completado', models.BooleanField(default=False, help_text='Indica si el recordatorio ha sido completado')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el recordatorio está activo')),
                ('moto', models.ForeignKey(help_text='Moto asociada al recordatorio', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_generales', to='core.moto')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario que registró el recordatorio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'recordatorio',
                'ordering': ['fecha_programada', 'titulo'],
            },
        ),
    ]
