# Generated by Django 4.2.7 on 2025-09-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recordatoriomantenimiento_activo_recordatorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recordatorio',
        ),
    ]
