# Generated by Django 4.2.7 on 2026-03-08 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_recordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatoriomantenimiento',
            name='registrado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que registró el recordatorio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorios_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
