# Generated migration for audit fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_recordatoriomantenimiento_registrado_por"),
    ]

    operations = [
        # Add audit fields to SoftDeleteModel (applies to all models inheriting from it)
        migrations.AddField(
            model_name="usuario",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuario_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuario_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuario_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to Persona
        migrations.AddField(
            model_name="persona",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to Rol
        migrations.AddField(
            model_name="rol",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rol_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="rol",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rol_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rol_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to UsuarioRol
        migrations.AddField(
            model_name="usuariorol",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuariorol_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="usuariorol",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="usuariorol",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuariorol_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="usuariorol",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuariorol_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to Categoria
        migrations.AddField(
            model_name="categoria",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categoria_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="categoria",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categoria_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categoria_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to CategoriaServicio
        migrations.AddField(
            model_name="categoriaservicio",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categoriaservicio_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="categoriaservicio",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="categoriaservicio",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categoriaservicio_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="categoriaservicio",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categoriaservicio_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to Proveedor
        migrations.AddField(
            model_name="proveedor",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proveedor_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proveedor_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proveedor_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to Producto
        migrations.AddField(
            model_name="producto",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="producto_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="producto_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="producto_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to Servicio
        migrations.AddField(
            model_name="servicio",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servicio_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servicio_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servicio_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to Moto
        migrations.AddField(
            model_name="moto",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moto_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="moto",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="moto",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moto_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="moto",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moto_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to Mantenimiento
        migrations.AddField(
            model_name="mantenimiento",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mantenimiento_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mantenimiento_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mantenimiento_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to DetalleMantenimiento
        migrations.AddField(
            model_name="detallemantenimiento",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detallemantenimiento_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="detallemantenimiento",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="detallemantenimiento",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detallemantenimiento_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="detallemantenimiento",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detallemantenimiento_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to RecordatorioMantenimiento
        migrations.AddField(
            model_name="recordatoriomantenimiento",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recordatoriomantenimiento_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="recordatoriomantenimiento",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="recordatoriomantenimiento",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recordatoriomantenimiento_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="recordatoriomantenimiento",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recordatoriomantenimiento_actualizados",
                to="core.usuario",
            ),
        ),
        # Add audit fields to RepuestoMantenimiento
        migrations.AddField(
            model_name="repuestomantenimiento",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que eliminó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repuestomantenimiento_eliminados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="repuestomantenimiento",
            name="fecha_eliminacion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="repuestomantenimiento",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que creó este registro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repuestomantenimiento_creados",
                to="core.usuario",
            ),
        ),
        migrations.AddField(
            model_name="repuestomantenimiento",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Usuario que realizó la última actualización",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repuestomantenimiento_actualizados",
                to="core.usuario",
            ),
        ),
    ]
