# Generated by Django 4.2.7 on 2026-03-20 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moto',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moto',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moto',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordatoriomantenimiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordatoriomantenimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordatoriomantenimiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repuestomantenimiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repuestomantenimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repuestomantenimiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rol',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rol',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rol',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que eliminó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL),
        ),
    ]
