# Generated by Django 4.2.7 on 2026-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_venta_creado_por_venta_descuento_venta_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemantenimiento',
            name='km_proximo_cambio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='tipo_aceite',
            field=models.CharField(blank=True, choices=[('mineral', 'Mineral'), ('semisintetico', 'Semisintético'), ('sintetico', 'Sintético')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recordatoriomantenimiento',
            name='km_proximo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordatoriomantenimiento',
            name='tipo',
            field=models.CharField(choices=[('km', 'Por Kilometraje'), ('fecha', 'Por Fecha')], default='fecha', max_length=10),
        ),
        migrations.AlterField(
            model_name='recordatoriomantenimiento',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
