# Generated by Django 4.2.7 on 2026-03-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recordatoriomantenimiento_notas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AlterModelOptions(
            name='recordatoriomantenimiento',
            options={'ordering': ['fecha_programada', 'km_proximo'], 'verbose_name': 'Recordatorio de Mantenimiento', 'verbose_name_plural': 'Recordatorios de Mantenimiento'},
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='completado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que completó el mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_completados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='correctivo', max_length=20),
        ),
        migrations.AddField(
            model_name='repuestomantenimiento',
            name='permitir_sin_stock',
            field=models.BooleanField(default=False, help_text='Permitir usar repuesto aunque no haya stock disponible'),
        ),
        migrations.AddIndex(
            model_name='recordatoriomantenimiento',
            index=models.Index(fields=['moto', 'activo'], name='recordatori_moto_id_451dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='recordatoriomantenimiento',
            index=models.Index(fields=['fecha_programada'], name='recordatori_fecha_p_09c420_idx'),
        ),
    ]
