# Generated by Django 4.2.7 on 2026-03-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_mantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Número de intentos de login fallidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, help_text='Último intento de login fallido', null=True),
        ),
    ]
