# Generated by Django 4.2.7 on 2026-03-25 01:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_venta_actualizado_por_venta_eliminado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='detalle_venta',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='procesado_por',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='venta',
        ),
        migrations.AlterUniqueTogether(
            name='preciocliente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='preciocliente',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='preciocliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='preciocliente',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='preciocliente',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='preciocliente',
            name='producto',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='costo_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo adicional por servicios extras o materiales no incluidos en repuestos', max_digits=10),
        ),
        migrations.DeleteModel(
            name='DetalleDevolucion',
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
        migrations.DeleteModel(
            name='PrecioCliente',
        ),
    ]
