# Generated by Django 4.2.7 on 2026-03-25 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_devolucion_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
