# Generated by Django 4.2.7 on 2026-04-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_optional_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
    ]
