# Generated by Django 4.2.7 on 2026-04-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_categorias_nombre_normalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
