# Generated by Django 4.2.7 on 2026-04-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_categoria_nombre_and_more'),
        ('core', '0023_categorias_nombre_sin_espacios'),
    ]

    operations = [
    ]
