# Generated by Django 4.2.7 on 2026-04-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20260412_2007'),
        ('core', '0024_servicio_nombre_sin_espacios'),
    ]

    operations = [
    ]
