# Generated by Django 4.2.7 on 2026-04-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20260412_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='kilometraje_salida',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje al salir la moto después del mantenimiento', null=True),
        ),
    ]
